### ISSUE TITLE
jemalloc absent in a system after installation

### ISSUE THREAD

**Issue by garry-t** [heroku/buildpacks-deb-packages#62]
I have started my journey recently with buildpacks. First issue I found that jemalloc doesn't work in my container
Manually checking path returns only
```
ls /usr/lib/x86_64-linux-gnu/libj
libjbig.so.0          libjbig2dec.so.0      libjbig2dec.so.0.0.0  libjpeg.so.8          libjpeg.so.8.2.2      libjq.so.1            libjq.so.1.0.4        libjson-c.so.5        libjson-c.so.5.1.0 
```
### project.toml
```
[_]
schema-version = "0.2"

# buildpack configuration goes here
[com.heroku.buildpacks.deb-packages]
install = [
    # string version of a dependency to install
    "libtag1-dev",
    "libjemalloc2"
]
```

**Comment by colincasey** [comment]
Hi @garry-t, thanks for opening this issue! 

This buildpack cannot install into `/usr/lib` for the reasons explained in the [README](https://github.com/heroku/buildpacks-deb-packages?tab=readme-ov-file#herokus-deb-packages-buildpack):

> This buildpack implements logic to install packages from .deb files in a CNB-friendly manner that does not require root permissions or modifications to system files that could invalidate how [CNB rebasing](https://buildpacks.io/docs/for-app-developers/concepts/rebase/) functionality works.

Because of these restrictions, packages are installed into a CNB layer, not into system directories. Currently this layer is located at `/layers/heroku_deb-packages/packages/` so you would check the path with:

```
ls /layers/heroku_deb-packages/packages//usr/lib/x86_64-linux-gnu/libj
```

Please let me know if that helps with your usage and configuration of jemalloc.

**Comment by garry-t** [comment]
@colincasey thanks for your reply. I will back to CNB task a bit later, but I think my a mistake was that during build I didnt specify `--descriptor project.toml` so it doesn't participate in DETECT stage. 
Closing for now.
